language: python

python:
  - 2.7

sudo: required

cache:
  - pip
  - apt

cache:
  directories:
  - $HOME/.cache


virtualenv:
  system_site_packages: true

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

before_install:
  - pip install ablog --cache-dir $HOME/.cache
  - sudo apt-get remove graphviz
  - sudo apt-get remove graphviz-dev
  - sudo apt-get remove graphviz-doc
  - sudo apt-get install graphviz

script:
  - dot -V
  - ablog build

after_success:
  - git config --global user.name "Xsoda"
  - git config --global user.email "Xsoda@live.com"
  - git config --global push.default simple
  - ablog deploy --push-quietly --github-token=TRAVIS_DEPLOY_TOKEN -m="`git log -1 --pretty=%B`"
