language: python

sudo: false

cache:
  directories:
  - $HOME/.cache/pip
  - $HOME/.cache/apt

addons:
  apt:
    sources:
    - deadsnakes
    - ubuntu-toolchain-r-test
    packages:
    - graphviz
  pip:
    packages:
    - ablog

python:
  - 2.7

virtualenv:
  system_site_packages: true

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

script:
  - ablog build

after_success:
  - git config --global user.name "Xsoda"
  - git config --global user.email "Xsoda@live.com"
  - git config --global push.default simple
  - ablog deploy --push-quietly --github-token=TRAVIS_DEPLOY_TOKEN -m="`git log -1 --pretty=%B`"
