language: python

before_install:
  - pip install ablog
  - pip install pygments-style-github
  - pip install sphinxcontrib-mermaid

script:
  - ablog build

after_success:
  - git config --global user.name "Xsoda"
  - git config --global user.email "Xsoda@live.com"
  - git config --global push.default simple
  - ablog deploy --push-quietly --github-ssh --github-token=TRAVIS_DEPLOY_TOKEN -m="`git log -1 --pretty=%B`"
